version: "2"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=Cisco!234
      - DOCKER_INFLUXDB_INIT_ORG=TMACO-LAB
      - DOCKER_INFLUXDB_INIT_BUCKET=3850-SWITCH-BUCKET
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=veryverysecuretoken
    volumes:
      - ./vols/:/var/lib/influxdb
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    links:
      - influxdb
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf:latest 
    ports:
      - "57000:57000"
    environment:
      - INFLUXDB_TOKEN=veryverysecuretoken
    links:
      - influxdb
    volumes:
      - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
