# Note: we are using DECLARATIVE IOS modules to create interfaces (abstracting away literal CLI commands)
---
- name: Create and address loopback interface
  hosts: iosxe
  gather_facts: no

  tasks:
  - name: Create loopback {{subnet_id}}
    cisco.ios.ios_interfaces:
      config:
      - name: Loopback{{subnet_id}}
        description: Pod Number {{subnet_id}}
        enabled: true
  - name: Assign IP to loopback
    cisco.ios.ios_l3_interfaces:
      config:
      - name: Loopback{{subnet_id}}
        ipv4:
        - address: 10.111.{{subnet_id}}.1/32