# Note: we are using IMPERATIVE IOS modules to create NTP and ACL config (specifying literal CLI commands)
---
- name: configure ntp and acl via CLI
  hosts: iosxe
  gather_facts: no

  tasks:
  - name: set ACL via CLI
    cisco.ios.ios_config:
      lines:
        - 10 permit ip host 1.1.1.1 any log
        - 20 permit ip host 2.2.2.2 any log
        - 30 permit ip host 3.3.3.3 any log
        - 40 permit ip host 4.4.4.4 any log
        - 50 permit ip host 5.5.5.5 any log
      parents: ['ip access-list extended my_acl']
      before: no ip access-list extended my_acl

  - name: set ntp server 10.1.{{subnet_id}}.{{item}} via CLI
    cisco.ios.ios_config:
      lines:
        - ntp server 10.1.{{subnet_id}}.{{item}}
    loop:
        - 11
        - 12
        - 13
        - 14